### ISSUE TITLE
Getting an error when attempting to run script

### ISSUE THREAD

**Issue by rcaldous** [nsip/registration-data-set#3]
I have all of the required perl modules installed however I get the following message when attempting to run the script 

![Screenshot_2021-12-04_07-46-32](https://user-images.githubusercontent.com/26811090/144670637-2d2b5474-515c-4d44-a052-263b5aef2c0b.png)

"(in cleanup) Can't call method "FETCH" on an undefined value at /usr/local/share/perl/5.32.1/Object/InsideOut.pm line 1953 during global destruction."

Any help in getting this resolved is most appreciated, I was intending to generate sample data for internal testing purposes.  
Just as a note I am able to get the nap_platformdata_generator.pl from the other repo working fine and have used this for testing.

System:
Linux Ubuntu 21.04
Perl 5.32.1

**Comment by opoudjis** [comment]
Richard, really sorry, did not notice this error report. Ugh.

I can replicate it, clearly something has gone wrong with Perl updates. (I'm now on Perl 5.34.) Investigating.

**Comment by opoudjis** [comment]
https://stackoverflow.com/questions/54005221/in-cleanup-cant-call-method-fetch-on-an-undefined-value-object-insideout-pm

The error report has been there in Perl for the past three years at least, and the only online acknowledgement of it is:

> This is mostly an inconsequential bug in Object::InsideOut. Perl tries to clean up the memory used by the objects and part of that memory has already been cleaned up. You can safely ignore that message.

The script does run successfully, as you will have already seen, and the error report only comes up in post-execution cleanup. So this can indeed be ignored.
